name: Update URLS
on:
  workflow_dispatch:
jobs:
  updateURLS:
    runs-on: ubuntu-latest
    env:
      STATUS_REPO: AdemZarrouki/ide-urls-status
      TEST_BRANCH: test/test-workflow
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout ide-urls-status (fork test branch)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.STATUS_REPO }}
          ref: ${{ env.TEST_BRANCH }}
          path: ide-urls-status
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          mvn -B -ntp -Dstyle.color=always -pl url-updater -am install
          mvn -B -ntp -Dstyle.color=always -pl url-updater exec:java \
            -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" \
            -Dexec.args="ide-urls-status PT5H30M squirrel-sql"
        env:
          ACTION_PUSH_TOKEN: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Commit and push to ide-urls-status (fork test branch)
        run: |
          cd ide-urls-status
          git config --global user.name "${{ secrets.BUILD_USER }}"
          git config --global user.email "${{ CBUILD_USER_EMAIL }}"
          if git status -z | grep -q .
          then
            git add .
            git commit -m "Test: update url status"
            git push origin HEAD:${{ env.TEST_BRANCH }}
          else
            echo "No changes, nothing to commit."
          fi
