name: Update URLS
on:
  workflow_dispatch:
jobs:
  updateURLS:
    runs-on: ubuntu-latest
    env:
      STATUS_REPO: AdemZarrouki/ide-urls-status
      TEST_BRANCH: test/test-workflow
      URLS_REPO: AdemZarrouki/ide-urls
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout ide-urls
        uses: actions/checkout@v3
        with:
          repository: ${{ env.URLS_REPO }}
          ref: ${{ env.TEST_BRANCH }}
          path: ide-urls
          token: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Checkout ide-urls-status (fork test branch)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.STATUS_REPO }}
          ref: ${{ env.TEST_BRANCH }}
          path: ide-urls-status
          token: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          mvn -B -ntp -Dstyle.color=always -pl url-updater -am install
          mvn -B -ntp -Dstyle.color=always -pl url-updater exec:java -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" -Dexec.args="ide-urls PT5H30M claude"
        env:
          ACTION_PUSH_TOKEN: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Commit and push only changed status.json files
        run: |
          cd ide-urls-status
          git config --global user.name "${{ secrets.BUILD_USER }}"
          git config --global user.email "${{ secrets.CBUILD_USER_EMAIL }}"
          CHANGED_STATUS_FILES=$(git status --porcelain | sed 's/^...//' | grep -E '(^|/)status\.json$'  || true)
          if [ -n "$CHANGED_STATUS_FILES" ]; then
            echo "Changed status.json files:"
            echo "$CHANGED_STATUS_FILES"
            echo "$CHANGED_STATUS_FILES" | while IFS= read -r file; do
              git add "$file"
            done
            git commit -m "Update status.json"
            git push origin HEAD:${{ env.TEST_BRANCH }}
          else
            echo "No changed status.json files"
          fi
      - name: Commit and push other files to ide-urls
        run: |
          cd ide-urls
          git config --global user.name "${{ secrets.BUILD_USER }}"
          git config --global user.email "${{ secrets.CBUILD_USER_EMAIL }}"
          CHANGED_NON_STATUS_FILES=$(git status --porcelain | sed 's/^...//' | grep -Ev '(^|/)status\.json$' || true)
          if [ -n "$CHANGED_NON_STATUS_FILES" ]; then
            echo "Changed non-status.json files:"
            echo "$CHANGED_NON_STATUS_FILES"
            while IFS= read -r file; do
              [ -n "$file" ] && git add "$file"
            done <<< "$CHANGED_NON_STATUS_FILES"
            git commit -m "Update URLs"
            git push origin HEAD:${{ env.TEST_BRANCH }}
          else
            echo "No non-status.json changes"
          fi

